backend:
  name: github
  repo: Jarivdberg/innego # Path to your GitHub repository
  branch: preview # Branch to update (master by default)

media_folder: "images/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "page" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Page" # Used in the UI, ie.: "New Post"
    folder: "source/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Introduction"
        name: "introduction"
        widget: "list"
        fields:
          - {label: Title, name: title, widget: string, default: "Introduction header"}
          - {label: Body, name: body, widget: markdown, default: "Lorem ipsum"}
          - {label: Image, name: image, widget: image}
      - label: "Services"
        name: "services"
        widget: "list"
        fields:
          - {label: Title, name: title, widget: string, default: "Introduction header"}
          - label: Service
            name: service
            widget: object
            fields:
              - {label: Title, name: title, widget: string, default: "Service"}
              - {label: Body, name: body, widget: text, default: "Lorem ipsum"}
              - {label: Duration, name: duration, widget: string, default: ""}
              - {label: Call to action text, name: call-to-action-text, widget: string, default: "Call to action"}
              - {label: Call to action link, name: call-to-action-link, widget: string, default: "#"}
      - label: "About"
        name: "about"
        widget: "list"
        fields:
          - {label: Title, name: title, widget: string, default: "Introduction header"}
          - {label: Left content, name: left-content, widget: markdown, default: ""}
          - {label: Right image, name: right-image, widget: image}
          - {label: Right content, name: right-content, widget: markdown, default: ""}
          - {label: Left image, name: left-image, widget: image}
      - label: "References"
        name: "references"
        widget: "list"
        fields:
          - {label: Title, name: title, widget: string, default: "Introduction header"}
          - label: Reference
            name: reference
            widget: object
            fields:
              - {label: Title, name: title, widget: string, default: "Service"}
              - {label: Body, name: body, widget: text, default: "Lorem ipsum"}
              - {label: Author, name: author, widget: string}
      - label: "Contact"
        name: "contact"
        widget: "list"
        fields:
          - {label: Title, name: title, widget: string, default: "Introduction header"}
          - {label: Body, name: body, widget: text, default: "Lorem ipsum"}
          - {label: Email, name: email, widget: text, default: "info@website.com"}

